# Generated by Django 2.1.4 on 2019-01-12 11:03

from django.db import migrations, models
import stack_overflow_clone.base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171024_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.CharField(blank=True, max_length=120, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=stack_overflow_clone.base.utils.upload_to, verbose_name='Profile Photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='reputation',
            field=models.PositiveIntegerField(default=0, verbose_name='Reputation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last login'),
        ),
    ]
